x-backend-env: &backend-env
  CELERY_BROKER_URL: redis://redis:6379
  CELERY_RESULT_BACKEND_URL: redis://redis:6379/0
  LOG_LEVEL: DEBUG

services:
  backend:
    image: ${DIPLOMA_BACKEND_IMAGE}
    command: uvicorn --reload backend.bootstrap:app --host 0.0.0.0 --port 8080
    restart: unless-stopped
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - './:/app'
    environment: *backend-env
    depends_on:
      - redis

  redis:
    image: redis:7.0-bullseye
    restart: unless-stopped

  celery_worker:
    image: ${DIPLOMA_BACKEND_IMAGE}
    command: watchmedo auto-restart --recursive -d backend/ -p '*.py' -- celery -A backend.tasks.app worker --loglevel=DEBUG
    volumes:
      - './:/app'
    restart: unless-stopped
    environment: *backend-env
    depends_on:
      - redis

  flower:
    image: ${DIPLOMA_BACKEND_IMAGE}
    command: celery -A backend.tasks.app flower --address=0.0.0.0
    ports:
      - '127.0.0.1:8082:5555'
    volumes:
      - './:/app'
    restart: unless-stopped
    environment: *backend-env
    depends_on:
      - celery_worker
